### ISSUE TITLE
Progress bar not updating when uploading large data file via `az ml data create`

### ISSUE THREAD

**Issue by shwars** [Azure/azureml-v2-preview#269]
## Describe the issue

When uploading large (800 Mb) tabular (CSV) file via `az ml data create -f`, the progress bar is shown at 0% (without any ETA estimations - see the image below), stays like that for a long time, and then instantly displays 100%. This behavior is rather confusing.

![image](https://user-images.githubusercontent.com/2892110/115782017-d60c1b80-a3c3-11eb-9350-a01fa8b0f6d6.png)

## Minimal example

I am using `metadata.csv` file from [this kaggle dataset](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge). yaml data file is the following:
```yaml
$schema: https://azuremlsdk2.blob.core.windows.net/latest/asset.schema.json
name: metacord
version: 1
local_path: metadata.csv
```
Command to upload is:
```bash
az ml data create -f data.yml
```

## Additional context

- az ml version: 0.0.67
- azure cli: 2.22.1
