### ISSUE TITLE
Job data binding is invalid or incomplete when using inputs in sweep job (in iris_sweep example)

### ISSUE THREAD

**Issue by shwars** [Azure/azureml-v2-preview#270]
## Describe the issue

I am trying to run a sweep job that has both sweep parameters and input data files (similar to **iris_sweep** example). The script is defined as follows: 
```yaml
trial:
  command: >-
    python process.py --number {search_space.number} --data {inputs.metacord}
```
Inputs are defined as follows:
```yaml
  inputs:
    metacord:
      data: azureml:metacord:1
      mode: download
```
I am getting the following error:
```
Code: UserError
Message: Job data binding metacord is invalid or incomplete.
```

The same problem occurs when I try to submit the `iris_sweep.yml` job from official examples.

## Minimal example

Complete job yaml file is below:
```yaml
$schema: https://azuremlsdk2.blob.core.windows.net/latest/sweepJob.schema.json
experiment_name: cog-sweep
algorithm: grid
type: sweep_job
search_space:
  number:
    type: choice
    values: [0, 1]
objective:
  primary_metric: processed
  goal: maximize
trial:
  command: >-
    python process.py --number {search_space.number} --data {inputs.metacord}
  code:
    local_path: .
  environment: azureml:AzureML-Minimal:1
  compute:
    target: azureml:AzMLCompute
  inputs:
    metacord:
      data: azureml:metacord:1
      mode: download
max_total_trials: 2
max_concurrent_trials: 2
timeout_minutes: 10000
```

## Additional context
 - az ml version: 0.0.67
 - azure cli: 2.22.1

AB#1142605
