### ISSUE TITLE
The YAML schema specs do not support inline environment definitions

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-v2-preview#92]
Try a simple job spec like this:

```yml
# yaml-language-server: $schema=https://azuremlsdk2.blob.core.windows.net/latest/commandJob.schema.json

experiment_name: azuremlv2

command: python train.py
environment:
  name: azuremlv2
  version: 1
  conda_file: environment.yml
```

The language server complains:

![image](https://user-images.githubusercontent.com/5003801/102284811-bd599980-3ee9-11eb-8dac-9cbef35efcff.png)

AB#991839
